roberta:
  pretrained: "andreas122001/roberta-academic-detector"
  finetuned: "/content/drive/MyDrive/roberta/roberta_finetune/saved_weights/model.safetensors"

bloomz:
  pretrained: "andreas122001/bloomz-560m-academic-detector"
  finetuned: "data/chatgpt_abstract_with_validation.jsonl"

xgboost:
  pretrained: "na"
  finetuned: "na"