roberta:
  pretrained: "andreas122001/roberta-academic-detector"
  finetuned: "/content/drive/MyDrive/modelForAttack.safetensors"

bloomz:
  pretrained: "andreas122001/bloomz-560m-academic-detector"
  finetuned: "/content/drive/MyDrive/model.safetensors"

xgboost:
  pretrained: "na"
  finetuned: "na"